package com.group4.ebusiness.controller;

import com.group4.ebusiness.ejb.EmailService;
import com.group4.ebusiness.ejb.UserEJB;
import com.group4.ebusiness.entity.User;
import jakarta.ejb.EJB;
import jakarta.enterprise.context.RequestScoped;
import jakarta.faces.application.FacesMessage;
import jakarta.faces.context.FacesContext;
import jakarta.inject.Named;

/**
 * Handles account recovery and password reset operations.
 * Recovery codes are generated by UserEJB and delivered through EmailService.
 */
@Named
@RequestScoped
public class RecoveryController {

    @EJB
    private UserEJB userEJB;
    
    @EJB
    private EmailService emailService;

    private String email;
    private String recoveryCode;
    private String newPassword;

    /**
    * Finds the account associated with the entered email,
    * generates a recovery code and sends it through FakeSMTP.
    */
    public String sendRecoveryCode() {

        User user = userEJB.createRecoveryCode(email);

        if (user == null) {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(
                            FacesMessage.SEVERITY_ERROR,
                            "Recovery failed",
                            "No account was found with that email."
                    )
            );

            return null;
        }

        emailService.sendEmail(
                user.getEmail(),
                "Group 4 e-Business Account Recovery",
                "Hello " + user.getFirstName()
                + ",\n\nYour recovery code is: "
                + user.getRecoveryCode()
                + "\n\nPlease use this code to reset your password."
        );

        FacesContext.getCurrentInstance()
            .getExternalContext()
            .getSessionMap()
            .put("recoveryEmail", user.getEmail());
        
        FacesContext.getCurrentInstance()
            .getExternalContext()
            .getSessionMap()
            .put("recoveryFirstName", user.getFirstName());

        FacesContext.getCurrentInstance()
            .getExternalContext()
            .getSessionMap()
            .put("recoveryLastName", user.getLastName());

        FacesContext.getCurrentInstance()
            .getExternalContext()
            .getSessionMap()
            .put("recoveryUsername", user.getUsername());

        return "resetPassword?faces-redirect=true";
    }

    /**
    * Validates the recovery code and updates the user's password.
    * Temporary recovery information is removed after a successful reset.
    */
    public String resetPassword() {

        FacesContext context = FacesContext.getCurrentInstance();

        String savedEmail = (String) context
                .getExternalContext()
                .getSessionMap()
                .get("recoveryEmail");

        if (savedEmail == null) {
            return null;
        }

        boolean success = userEJB.resetPassword(
                savedEmail,
                recoveryCode,
                newPassword
        );

        // Clear temporary recovery data after the password has been changed.
        if (success) {

            context.getExternalContext()
                .getSessionMap()
                .remove("recoveryEmail");
            
            context.getExternalContext()
                .getSessionMap()
                .remove("recoveryFirstName");

            context.getExternalContext()
                .getSessionMap()
                .remove("recoveryLastName");

            context.getExternalContext()
                .getSessionMap()
                .remove("recoveryUsername");

            return "login?faces-redirect=true";
        }

        context.addMessage(
                null,
                new FacesMessage(
                        FacesMessage.SEVERITY_ERROR,
                        "Reset failed",
                        "Invalid recovery code."
                )
        );

        return null;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRecoveryCode() {
        return recoveryCode;
    }

    public void setRecoveryCode(String recoveryCode) {
        this.recoveryCode = recoveryCode;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }
}